### PR TITLE
add bits to create firehose in this account

### PR DESCRIPTION
**Pull request by brandon-dacrib**

### CODE REVIEW

**Comment by brandon-dacrib** [comment]
atlantis plan

**Comment by meetup-data-platform** [comment]
Ran Plan for 0 projects:

**Comment by meetup-data-platform** [comment]
Ran Plan for project: `streams` dir: `tf/streams` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.57.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.57"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_iam_role.k8s-analytics-prod_role
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      assume_role_policy:                                                                               "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"firehose.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\",\n      \"Sid\": \"\"\n    }\n  ]\n}\n"
      create_date:                                                                                      <computed>
      force_detach_policies:                                                                            "false"
      max_session_duration:                                                                             "3600"
      name:                                                                                             "k8s-analytics-prod_role"
      path:                                                                                             "/"
      unique_id:                                                                                        <computed>

  + aws_kinesis_firehose_delivery_stream.k8s-analytics-prod
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      destination:                                                                                      "extended_s3"
      destination_id:                                                                                   <computed>
      extended_s3_configuration.#:                                                                      "1"
      extended_s3_configuration.0.bucket_arn:                                                           "arn:aws:s3:::com.meetup.firehose"
      extended_s3_configuration.0.buffer_interval:                                                      "300"
      extended_s3_configuration.0.buffer_size:                                                          "5"
      extended_s3_configuration.0.cloudwatch_logging_options.#:                                         <computed>
      extended_s3_configuration.0.compression_format:                                                   "UNCOMPRESSED"
      extended_s3_configuration.0.prefix:                                                               "k8s-analytics-prod/"
      extended_s3_configuration.0.processing_configuration.#:                                           "1"
      extended_s3_configuration.0.processing_configuration.0.enabled:                                   "true"
      extended_s3_configuration.0.processing_configuration.0.processors.#:                              "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.#:                 "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_name:  "LambdaArn"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_value: "arn:aws:lambda:us-east-1:856721882819:function:firehose-avro-transformer-prod-transform:$LATEST"
      extended_s3_configuration.0.processing_configuration.0.processors.0.type:                         "Lambda"
      extended_s3_configuration.0.role_arn:                                                             "${aws_iam_role.k8s-analytics-prod_role.arn}"
      extended_s3_configuration.0.s3_backup_mode:                                                       "Disabled"
      name:                                                                                             "k8s-analytics-prod"
      version_id:                                                                                       <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p streams`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.shared-eks.meetuphq.io/lock?id=meetup%252Ffirehose-avro-transformer%252Ftf%252Fstreams%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p streams`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by brandon-dacrib** [comment]
atlantis apply

**Comment by meetup-data-platform** [comment]
Ran Apply for 0 projects:

**Comment by brandon-dacrib** [comment]
atlantis apply -p streams

**Comment by meetup-data-platform** [comment]
Ran Apply for project: `streams` dir: `tf/streams` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
exit status 1: running "terraform apply -input=false -no-color" in "/home/atlantis/.atlantis/repos/meetup/firehose-avro-transformer/6/default/tf/streams": 

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_iam_role.k8s-analytics-prod_role
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      assume_role_policy:                                                                               "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"firehose.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\",\n      \"Sid\": \"\"\n    }\n  ]\n}\n"
      create_date:                                                                                      <computed>
      force_detach_policies:                                                                            "false"
      max_session_duration:                                                                             "3600"
      name:                                                                                             "k8s-analytics-prod_role"
      path:                                                                                             "/"
      unique_id:                                                                                        <computed>

  + aws_kinesis_firehose_delivery_stream.k8s-analytics-prod
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      destination:                                                                                      "extended_s3"
      destination_id:                                                                                   <computed>
      extended_s3_configuration.#:                                                                      "1"
      extended_s3_configuration.0.bucket_arn:                                                           "arn:aws:s3:::com.meetup.firehose"
      extended_s3_configuration.0.buffer_interval:                                                      "300"
      extended_s3_configuration.0.buffer_size:                                                          "5"
      extended_s3_configuration.0.cloudwatch_logging_options.#:                                         <computed>
      extended_s3_configuration.0.compression_format:                                                   "UNCOMPRESSED"
      extended_s3_configuration.0.prefix:                                                               "k8s-analytics-prod/"
      extended_s3_configuration.0.processing_configuration.#:                                           "1"
      extended_s3_configuration.0.processing_configuration.0.enabled:                                   "true"
      extended_s3_configuration.0.processing_configuration.0.processors.#:                              "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.#:                 "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_name:  "LambdaArn"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_value: "arn:aws:lambda:us-east-1:856721882819:function:firehose-avro-transformer-prod-transform:$LATEST"
      extended_s3_configuration.0.processing_configuration.0.processors.0.type:                         "Lambda"
      extended_s3_configuration.0.role_arn:                                                             "${aws_iam_role.k8s-analytics-prod_role.arn}"
      extended_s3_configuration.0.s3_backup_mode:                                                       "Disabled"
      name:                                                                                             "k8s-analytics-prod"
      version_id:                                                                                       <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 

Error: Apply cancelled.




An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_iam_role.k8s-analytics-prod_role
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      assume_role_policy:                                                                               "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"firehose.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\",\n      \"Sid\": \"\"\n    }\n  ]\n}\n"
      create_date:                                                                                      <computed>
      force_detach_policies:                                                                            "false"
      max_session_duration:                                                                             "3600"
      name:                                                                                             "k8s-analytics-prod_role"
      path:                                                                                             "/"
      unique_id:                                                                                        <computed>

  + aws_kinesis_firehose_delivery_stream.k8s-analytics-prod
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      destination:                                                                                      "extended_s3"
      destination_id:                                                                                   <computed>
      extended_s3_configuration.#:                                                                      "1"
      extended_s3_configuration.0.bucket_arn:                                                           "arn:aws:s3:::com.meetup.firehose"
      extended_s3_configuration.0.buffer_interval:                                                      "300"
      extended_s3_configuration.0.buffer_size:                                                          "5"
      extended_s3_configuration.0.cloudwatch_logging_options.#:                                         <computed>
      extended_s3_configuration.0.compression_format:                                                   "UNCOMPRESSED"
      extended_s3_configuration.0.prefix:                                                               "k8s-analytics-prod/"
      extended_s3_configuration.0.processing_configuration.#:                                           "1"
      extended_s3_configuration.0.processing_configuration.0.enabled:                                   "true"
      extended_s3_configuration.0.processing_configuration.0.processors.#:                              "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.#:                 "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_name:  "LambdaArn"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_value: "arn:aws:lambda:us-east-1:856721882819:function:firehose-avro-transformer-prod-transform:$LATEST"
      extended_s3_configuration.0.processing_configuration.0.processors.0.type:                         "Lambda"
      extended_s3_configuration.0.role_arn:                                                             "${aws_iam_role.k8s-analytics-prod_role.arn}"
      extended_s3_configuration.0.s3_backup_mode:                                                       "Disabled"
      name:                                                                                             "k8s-analytics-prod"
      version_id:                                                                                       <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 

Error: Apply cancelled.



```
</details>

**Comment by meetup-data-platform** [comment]
Ran Plan for project: `streams` dir: `tf/streams` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.57.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.57"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_iam_role.k8s-analytics-prod_role
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      assume_role_policy:                                                                               "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"firehose.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\",\n      \"Sid\": \"\"\n    }\n  ]\n}\n"
      create_date:                                                                                      <computed>
      force_detach_policies:                                                                            "false"
      max_session_duration:                                                                             "3600"
      name:                                                                                             "k8s-analytics-prod_role"
      path:                                                                                             "/"
      unique_id:                                                                                        <computed>

  + aws_kinesis_firehose_delivery_stream.k8s-analytics-prod
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      destination:                                                                                      "extended_s3"
      destination_id:                                                                                   <computed>
      extended_s3_configuration.#:                                                                      "1"
      extended_s3_configuration.0.bucket_arn:                                                           "arn:aws:s3:::com.meetup.firehose"
      extended_s3_configuration.0.buffer_interval:                                                      "300"
      extended_s3_configuration.0.buffer_size:                                                          "5"
      extended_s3_configuration.0.cloudwatch_logging_options.#:                                         <computed>
      extended_s3_configuration.0.compression_format:                                                   "UNCOMPRESSED"
      extended_s3_configuration.0.prefix:                                                               "k8s-analytics-prod/"
      extended_s3_configuration.0.processing_configuration.#:                                           "1"
      extended_s3_configuration.0.processing_configuration.0.enabled:                                   "true"
      extended_s3_configuration.0.processing_configuration.0.processors.#:                              "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.#:                 "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_name:  "LambdaArn"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_value: "arn:aws:lambda:us-east-1:856721882819:function:firehose-avro-transformer-prod-transform:$LATEST"
      extended_s3_configuration.0.processing_configuration.0.processors.0.type:                         "Lambda"
      extended_s3_configuration.0.role_arn:                                                             "${aws_iam_role.k8s-analytics-prod_role.arn}"
      extended_s3_configuration.0.s3_backup_mode:                                                       "Disabled"
      name:                                                                                             "k8s-analytics-prod"
      version_id:                                                                                       <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p streams`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.shared-eks.meetuphq.io/lock?id=meetup%252Ffirehose-avro-transformer%252Ftf%252Fstreams%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p streams`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by brandon-dacrib** [comment]
atlantis apply

**Comment by meetup-data-platform** [comment]
Ran Apply for 0 projects:

**Comment by brandon-dacrib** [comment]
atlantis apply -p streams

**Comment by meetup-data-platform** [comment]
Ran Apply for project: `streams` dir: `tf/streams` workspace: `default`

**Apply Error**
```
no plan found at path "tf/streams" and workspace "default"–did you run plan?

```

**Comment by brandon-dacrib** [comment]
atlantis plan

**Comment by meetup-data-platform** [comment]
Ran Plan for project: `streams` dir: `tf/streams` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.57"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_iam_role.k8s-analytics-prod_role
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      assume_role_policy:                                                                               "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"firehose.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\",\n      \"Sid\": \"\"\n    }\n  ]\n}\n"
      create_date:                                                                                      <computed>
      force_detach_policies:                                                                            "false"
      max_session_duration:                                                                             "3600"
      name:                                                                                             "k8s-analytics-prod_role"
      path:                                                                                             "/"
      unique_id:                                                                                        <computed>

  + aws_kinesis_firehose_delivery_stream.k8s-analytics-prod
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      destination:                                                                                      "extended_s3"
      destination_id:                                                                                   <computed>
      extended_s3_configuration.#:                                                                      "1"
      extended_s3_configuration.0.bucket_arn:                                                           "arn:aws:s3:::com.meetup.firehose"
      extended_s3_configuration.0.buffer_interval:                                                      "300"
      extended_s3_configuration.0.buffer_size:                                                          "5"
      extended_s3_configuration.0.cloudwatch_logging_options.#:                                         <computed>
      extended_s3_configuration.0.compression_format:                                                   "UNCOMPRESSED"
      extended_s3_configuration.0.prefix:                                                               "k8s-analytics-prod/"
      extended_s3_configuration.0.processing_configuration.#:                                           "1"
      extended_s3_configuration.0.processing_configuration.0.enabled:                                   "true"
      extended_s3_configuration.0.processing_configuration.0.processors.#:                              "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.#:                 "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_name:  "LambdaArn"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_value: "arn:aws:lambda:us-east-1:856721882819:function:firehose-avro-transformer-prod-transform:$LATEST"
      extended_s3_configuration.0.processing_configuration.0.processors.0.type:                         "Lambda"
      extended_s3_configuration.0.role_arn:                                                             "${aws_iam_role.k8s-analytics-prod_role.arn}"
      extended_s3_configuration.0.s3_backup_mode:                                                       "Disabled"
      name:                                                                                             "k8s-analytics-prod"
      version_id:                                                                                       <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p streams`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.shared-eks.meetuphq.io/lock?id=meetup%252Ffirehose-avro-transformer%252Ftf%252Fstreams%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p streams`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by brandon-dacrib** [comment]
atlantis apply -p streams

**Comment by meetup-data-platform** [comment]
Ran Apply for project: `streams` dir: `tf/streams` workspace: `default`

**Apply Error**
```
no plan found at path "tf/streams" and workspace "default"–did you run plan?

```

**Comment by meetup-data-platform** [comment]
Ran Plan for project: `streams` dir: `tf/streams` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.57.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.57"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_iam_role.k8s-analytics-prod_role
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      assume_role_policy:                                                                               "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"firehose.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\",\n      \"Sid\": \"\"\n    }\n  ]\n}\n"
      create_date:                                                                                      <computed>
      force_detach_policies:                                                                            "false"
      max_session_duration:                                                                             "3600"
      name:                                                                                             "k8s-analytics-prod_role"
      path:                                                                                             "/"
      unique_id:                                                                                        <computed>

  + aws_kinesis_firehose_delivery_stream.k8s-analytics-prod
      id:                                                                                               <computed>
      arn:                                                                                              <computed>
      destination:                                                                                      "extended_s3"
      destination_id:                                                                                   <computed>
      extended_s3_configuration.#:                                                                      "1"
      extended_s3_configuration.0.bucket_arn:                                                           "arn:aws:s3:::com.meetup.firehose"
      extended_s3_configuration.0.buffer_interval:                                                      "300"
      extended_s3_configuration.0.buffer_size:                                                          "5"
      extended_s3_configuration.0.cloudwatch_logging_options.#:                                         <computed>
      extended_s3_configuration.0.compression_format:                                                   "UNCOMPRESSED"
      extended_s3_configuration.0.prefix:                                                               "k8s-analytics-prod/"
      extended_s3_configuration.0.processing_configuration.#:                                           "1"
      extended_s3_configuration.0.processing_configuration.0.enabled:                                   "true"
      extended_s3_configuration.0.processing_configuration.0.processors.#:                              "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.#:                 "1"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_name:  "LambdaArn"
      extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_value: "arn:aws:lambda:us-east-1:856721882819:function:firehose-avro-transformer-prod-transform:$LATEST"
      extended_s3_configuration.0.processing_configuration.0.processors.0.type:                         "Lambda"
      extended_s3_configuration.0.role_arn:                                                             "${aws_iam_role.k8s-analytics-prod_role.arn}"
      extended_s3_configuration.0.s3_backup_mode:                                                       "Disabled"
      name:                                                                                             "k8s-analytics-prod"
      version_id:                                                                                       <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p streams`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.shared-eks.meetuphq.io/lock?id=meetup%252Ffirehose-avro-transformer%252Ftf%252Fstreams%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p streams`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by brandon-dacrib** [comment]
atlantis apply

**Comment by brandon-dacrib** [comment]
atlantis apply -p streams

**Comment by meetup-data-platform** [comment]
Ran Apply for project: `streams` dir: `tf/streams` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_iam_role.k8s-analytics-prod_role: Creating...
  arn:                   "" => "<computed>"
  assume_role_policy:    "" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"firehose.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\",\n      \"Sid\": \"\"\n    }\n  ]\n}\n"
  create_date:           "" => "<computed>"
  force_detach_policies: "" => "false"
  max_session_duration:  "" => "3600"
  name:                  "" => "k8s-analytics-prod_role"
  path:                  "" => "/"
  unique_id:             "" => "<computed>"
aws_iam_role.k8s-analytics-prod_role: Creation complete after 0s (ID: k8s-analytics-prod_role)
aws_kinesis_firehose_delivery_stream.k8s-analytics-prod: Creating...
  arn:                                                                                              "" => "<computed>"
  destination:                                                                                      "" => "extended_s3"
  destination_id:                                                                                   "" => "<computed>"
  extended_s3_configuration.#:                                                                      "" => "1"
  extended_s3_configuration.0.bucket_arn:                                                           "" => "arn:aws:s3:::com.meetup.firehose"
  extended_s3_configuration.0.buffer_interval:                                                      "" => "300"
  extended_s3_configuration.0.buffer_size:                                                          "" => "5"
  extended_s3_configuration.0.cloudwatch_logging_options.#:                                         "" => "<computed>"
  extended_s3_configuration.0.compression_format:                                                   "" => "UNCOMPRESSED"
  extended_s3_configuration.0.prefix:                                                               "" => "k8s-analytics-prod/"
  extended_s3_configuration.0.processing_configuration.#:                                           "" => "1"
  extended_s3_configuration.0.processing_configuration.0.enabled:                                   "" => "true"
  extended_s3_configuration.0.processing_configuration.0.processors.#:                              "" => "1"
  extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.#:                 "" => "1"
  extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_name:  "" => "LambdaArn"
  extended_s3_configuration.0.processing_configuration.0.processors.0.parameters.0.parameter_value: "" => "arn:aws:lambda:us-east-1:856721882819:function:firehose-avro-transformer-prod-transform:$LATEST"
  extended_s3_configuration.0.processing_configuration.0.processors.0.type:                         "" => "Lambda"
  extended_s3_configuration.0.role_arn:                                                             "" => "arn:aws:iam::856721882819:role/k8s-analytics-prod_role"
  extended_s3_configuration.0.s3_backup_mode:                                                       "" => "Disabled"
  name:                                                                                             "" => "k8s-analytics-prod"
  version_id:                                                                                       "" => "<computed>"
aws_kinesis_firehose_delivery_stream.k8s-analytics-prod: Still creating... (10s elapsed)
aws_kinesis_firehose_delivery_stream.k8s-analytics-prod: Still creating... (20s elapsed)
aws_kinesis_firehose_delivery_stream.k8s-analytics-prod: Still creating... (30s elapsed)
aws_kinesis_firehose_delivery_stream.k8s-analytics-prod: Still creating... (40s elapsed)
aws_kinesis_firehose_delivery_stream.k8s-analytics-prod: Creation complete after 45s (ID: arn:aws:firehose:us-east-1:856721882819:deliverystream/k8s-analytics-prod)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
</details>

**Comment by meetup-data-platform** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `tf/streams` workspace: `default`

**Pull request merged**
